###
GET http://127.0.0.1:8080/paint

###
POST  http://127.0.0.1:8080/paint/create
Content-Type: application/json

{
  "userID" : "11",
  "imagePath" : "file:/Users/gloriadukuzeyesu/Downloads/cat.jpeg",
  "title" : "Cute cat"
}

### Get the image object with the specified ID
GET http://127.0.0.1:8080/paint/paintId?paintId=1

### Get images created by this user
GET http://127.0.0.1:8080/paint/userId?userID=10
Accept: application/json


### Delete image created by the user
DELETE http://127.0.0.1:8080/paint/delete?paintId=3

###
GET  http://127.0.0.1:8080/paint/d1e37cbe-4e0e-468c-8276-c0254665b865.png/getImage